### ISSUE TITLE
마지막 Todo

### ISSUE THREAD

**Issue by sihyeong671** [sihyeong671/DACON-CV02#23]
### merge code
- [x] main branch> cut mix 기능 추가 필요
- [x] main branch> transform 단일화(박시형 ver)
- [x] main branch> data feed, hyperparam, ..etc 단일화
- [x] main branch 기준으로 신규 브랜치 생성, case별 개별 모델 class생성

### IDEA
 - softvoting 구현
 - size, non_size
 - rgb, non_rgb
 - CE
 - sampling,
### CODE
 - code
### MORE

EPOCH 40, scheduler_step(decay=0.1) 30, 전체 데이터로 학습, sampling하기, seed => 653
efficientnet_b4(박시형)
- [x] non_size, non_rgb, CE
- [x] non_size, rgb, CE
- [x] size, non_rgb, CE
- [x] size, rgb, CE

EPOCH 45, scheduler_step(decay=0.1) 30, 전체 데이터로 학습, sampling하기, seed => 653
maxvit_t(김형석)
- [x] non_size, non_rgb, CE
- [x] non_size, rgb, CE
- [x] size, non_rgb, CE
- [x] size, rgb, CE

EPOCH 45, scheduler_step(decay=0.1) 30, 전체 데이터로 학습, sampling하기, seed => 653
resnext101_32x8d(정혁기)
- [x] non_size, non_rgb, CE
- [x] non_size, rgb, CE
- [x] size, non_rgb, CE
- [x] size, rgb, CE
