### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by sihyeong671** [sihyeong671/DACON-CV02#3]
- [x] 사진 크기 시각화 데이터 올리기
- [x] VIT 코드 올리기
- [x] 앙상블 기법 사용하기
- [x] lr 낮춰서 다시 학습시키기
- [x] 이미지 크기와 화가의 관계

~사진 비율 맞춰서 input 넣기 :batch 때문에 불가능~
